### PR TITLE
Use recommended cloudformation interval

### PR DESCRIPTION
**Pull request by JeffDownie**
See https://docs.aws.amazon.com/cli/latest/reference/cloudformation/wait/stack-create-complete.html

Helps with https://github.com/robertstettner/drone-cloudformation/issues/7 as well!

### CODE REVIEW

**Comment by stefano-b2c2** [comment]
@JeffDownie If you rebase against the new version then that build error will disappear.

**Comment by JeffDownie** [comment]
@stefano-b2c2 I'll give it a go, but looking at the diffs of your PR I don't see where it would have addressed the issue?

EDIT:

Ignore me, I thought you said the actual issue itself disappeared due to your PR, nvm

**Comment by svozza** [comment]
Nah, the old version was using a fork of `cfn` from Neville but that seems to have disappeared so we're using my fork now.

**Comment by svozza** [comment]
And as it happens my PR for `cfn` has just been merged so we can use the latest version of that from npm now.

**Comment by JeffDownie** [comment]
Closing as no longer necessary !

**Pull request closed without merging**
